pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out project from GitHub repository'
                git branch: 'main', url: 'https://github.com/Lohith22222/8.2CDevSecOps.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing Node.js project dependencies'
                bat 'call npm install'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Executing application test cases'
                bat 'call npm test || exit /b 0'
            }
        }

        stage('Generate Coverage Report') {
            steps {
                echo 'Generating code coverage report'
                bat 'call npm run coverage || exit /b 0'
            }
        }

        stage('Security Scan') {
            steps {
                echo 'Performing npm audit security scan'
                bat 'call npm audit || exit /b 0'
            }
        }
    }

    post {

        success {
            emailext(
                subject: "Jenkins Pipeline Success - ${env.JOB_NAME} #${env.BUILD_NUMBER}",

                body: """
Hello,

This is an automated email notification generated by the Jenkins Extended Email Plugin.

The DevSecOps pipeline has completed successfully.

Build Details:
--------------------------------------------------
Job Name       : ${env.JOB_NAME}
Build Number   : ${env.BUILD_NUMBER}
Build Status   : SUCCESS
Build URL      : ${env.BUILD_URL}
--------------------------------------------------

The following stages were executed successfully:
1. Checkout Source Code
2. Install Dependencies
3. Run Application Tests
4. Generate Coverage Report
5. Perform Security Scan using npm audit

The complete Jenkins console log has been attached to this email for verification, monitoring, and auditing purposes.

Regards,
Jenkins Automation Server
""",

                to: "lohith2823@gmail.com",

                attachLog: true
            )
        }

        failure {
            emailext(
                subject: "Jenkins Pipeline Failed - ${env.JOB_NAME} #${env.BUILD_NUMBER}",

                body: """
Hello,

This is an automated email notification generated by the Jenkins Extended Email Plugin.

The DevSecOps pipeline execution has failed.

Build Details:
--------------------------------------------------
Job Name       : ${env.JOB_NAME}
Build Number   : ${env.BUILD_NUMBER}
Build Status   : FAILURE
Build URL      : ${env.BUILD_URL}
--------------------------------------------------

One or more stages in the pipeline failed during execution. Please review the attached Jenkins console log to identify the cause of the failure and investigate the reported errors.

The attached log file contains detailed execution information, including test outputs and security scan results.

Regards,
Jenkins Automation Server
""",

                to: "lohith2823@gmail.com",

                attachLog: true
            )
        }

        always {
            echo 'Pipeline execution completed'
        }
    }
}
